-- Sample data for LOCAL development only (supabase db reset / supabase start).
-- Reference data the application requires lives in migrations (0005), because
-- `supabase db push` never applies this file. Nothing here yet: real courts,
-- availability, products and terms are Artur's data, entered through the console.
