// GENERATED by scripts/gen-db-types.mjs from supabase/migrations — do not edit.
// Regenerate with: pnpm db:types
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
	public: {
		Tables: {
			academy_settings: {
				Row: {
					id: boolean
					timezone: string
					camp_season_start: string | null
					camp_season_end: string | null
					cancel_notice_hours: number
					booking_horizon_days: number
					default_credit_validity_days: number
					low_credit_threshold: number
					default_forgiven_skips: number
					updated_at: string
				}
				Insert: {
					id?: boolean
					timezone?: string
					camp_season_start?: string | null
					camp_season_end?: string | null
					cancel_notice_hours?: number
					booking_horizon_days?: number
					default_credit_validity_days?: number
					low_credit_threshold?: number
					default_forgiven_skips?: number
					updated_at?: string
				}
				Update: {
					id?: boolean
					timezone?: string
					camp_season_start?: string | null
					camp_season_end?: string | null
					cancel_notice_hours?: number
					booking_horizon_days?: number
					default_credit_validity_days?: number
					low_credit_threshold?: number
					default_forgiven_skips?: number
					updated_at?: string
				}
				Relationships: []
			}
			accounts: {
				Row: {
					id: string
					email: string
					full_name: string
					phone: string | null
					created_at: string
					updated_at: string
				}
				Insert: {
					id: string
					email: string
					full_name?: string
					phone?: string | null
					created_at?: string
					updated_at?: string
				}
				Update: {
					id?: string
					email?: string
					full_name?: string
					phone?: string | null
					created_at?: string
					updated_at?: string
				}
				Relationships: [
					{
						foreignKeyName: "accounts_id_fkey"
						columns: ["id"]
						isOneToOne: false
						referencedRelation: "users"
						referencedColumns: ["id"]
					}
				]
			}
			audit_log: {
				Row: {
					id: string
					actor: string | null
					action: string
					entity_type: string
					entity_id: string | null
					before: Json | null
					after: Json | null
					at: string
				}
				Insert: {
					id?: string
					actor?: string | null
					action: string
					entity_type: string
					entity_id?: string | null
					before?: Json | null
					after?: Json | null
					at?: string
				}
				Update: {
					id?: string
					actor?: string | null
					action?: string
					entity_type?: string
					entity_id?: string | null
					before?: Json | null
					after?: Json | null
					at?: string
				}
				Relationships: []
			}
			camp_registrations: {
				Row: {
					id: string
					camp_id: string
					player_id: string
					order_item_id: string | null
					status: Database["public"]["Enums"]["registration_status"]
					created_at: string
					updated_at: string
				}
				Insert: {
					id?: string
					camp_id: string
					player_id: string
					order_item_id?: string | null
					status?: Database["public"]["Enums"]["registration_status"]
					created_at?: string
					updated_at?: string
				}
				Update: {
					id?: string
					camp_id?: string
					player_id?: string
					order_item_id?: string | null
					status?: Database["public"]["Enums"]["registration_status"]
					created_at?: string
					updated_at?: string
				}
				Relationships: [
					{
						foreignKeyName: "camp_reg_order_item_fk"
						columns: ["order_item_id"]
						isOneToOne: false
						referencedRelation: "order_items"
						referencedColumns: ["id"]
					},
					{
						foreignKeyName: "camp_registrations_camp_id_fkey"
						columns: ["camp_id"]
						isOneToOne: false
						referencedRelation: "camps"
						referencedColumns: ["id"]
					},
					{
						foreignKeyName: "camp_registrations_player_id_fkey"
						columns: ["player_id"]
						isOneToOne: false
						referencedRelation: "players"
						referencedColumns: ["id"]
					}
				]
			}
			camp_sessions: {
				Row: {
					session_id: string
					session_type: Database["public"]["Enums"]["session_type"]
					camp_id: string
				}
				Insert: {
					session_id: string
					session_type?: Database["public"]["Enums"]["session_type"]
					camp_id: string
				}
				Update: {
					session_id?: string
					session_type?: Database["public"]["Enums"]["session_type"]
					camp_id?: string
				}
				Relationships: [
					{
						foreignKeyName: "camp_sessions_camp_id_fkey"
						columns: ["camp_id"]
						isOneToOne: false
						referencedRelation: "camps"
						referencedColumns: ["id"]
					},
					{
						foreignKeyName: "camp_sessions_session_id_session_type_fkey"
						columns: ["session_id", "session_type"]
						isOneToOne: false
						referencedRelation: "sessions"
						referencedColumns: ["id", "session_type"]
					}
				]
			}
			camps: {
				Row: {
					id: string
					name: string
					starts_on: string
					ends_on: string
					capacity: number
					product_id: string | null
					description: string | null
					created_at: string
				}
				Insert: {
					id?: string
					name: string
					starts_on: string
					ends_on: string
					capacity: number
					product_id?: string | null
					description?: string | null
					created_at?: string
				}
				Update: {
					id?: string
					name?: string
					starts_on?: string
					ends_on?: string
					capacity?: number
					product_id?: string | null
					description?: string | null
					created_at?: string
				}
				Relationships: [
					{
						foreignKeyName: "camps_product_id_fkey"
						columns: ["product_id"]
						isOneToOne: false
						referencedRelation: "products"
						referencedColumns: ["id"]
					}
				]
			}
			class_bookings: {
				Row: {
					id: string
					class_session_id: string
					player_id: string
					booked_by_account_id: string
					status: Database["public"]["Enums"]["booking_status"]
					scope: Database["public"]["Enums"]["credit_scope"]
					week_start: string
					created_at: string
					updated_at: string
				}
				Insert: {
					id?: string
					class_session_id: string
					player_id: string
					booked_by_account_id: string
					status?: Database["public"]["Enums"]["booking_status"]
					scope: Database["public"]["Enums"]["credit_scope"]
					week_start: string
					created_at?: string
					updated_at?: string
				}
				Update: {
					id?: string
					class_session_id?: string
					player_id?: string
					booked_by_account_id?: string
					status?: Database["public"]["Enums"]["booking_status"]
					scope?: Database["public"]["Enums"]["credit_scope"]
					week_start?: string
					created_at?: string
					updated_at?: string
				}
				Relationships: [
					{
						foreignKeyName: "class_bookings_booked_by_account_id_fkey"
						columns: ["booked_by_account_id"]
						isOneToOne: false
						referencedRelation: "accounts"
						referencedColumns: ["id"]
					},
					{
						foreignKeyName: "class_bookings_class_session_id_fkey"
						columns: ["class_session_id"]
						isOneToOne: false
						referencedRelation: "class_sessions"
						referencedColumns: ["session_id"]
					},
					{
						foreignKeyName: "class_bookings_player_id_fkey"
						columns: ["player_id"]
						isOneToOne: false
						referencedRelation: "players"
						referencedColumns: ["id"]
					}
				]
			}
			class_sessions: {
				Row: {
					session_id: string
					session_type: Database["public"]["Enums"]["session_type"]
					class_id: string
				}
				Insert: {
					session_id: string
					session_type?: Database["public"]["Enums"]["session_type"]
					class_id: string
				}
				Update: {
					session_id?: string
					session_type?: Database["public"]["Enums"]["session_type"]
					class_id?: string
				}
				Relationships: [
					{
						foreignKeyName: "class_sessions_class_id_fkey"
						columns: ["class_id"]
						isOneToOne: false
						referencedRelation: "classes"
						referencedColumns: ["id"]
					},
					{
						foreignKeyName: "class_sessions_session_id_session_type_fkey"
						columns: ["session_id", "session_type"]
						isOneToOne: false
						referencedRelation: "sessions"
						referencedColumns: ["id", "session_type"]
					}
				]
			}
			class_skill_levels: {
				Row: {
					class_id: string
					skill_level_id: string
				}
				Insert: {
					class_id: string
					skill_level_id: string
				}
				Update: {
					class_id?: string
					skill_level_id?: string
				}
				Relationships: [
					{
						foreignKeyName: "class_skill_levels_class_id_fkey"
						columns: ["class_id"]
						isOneToOne: false
						referencedRelation: "classes"
						referencedColumns: ["id"]
					},
					{
						foreignKeyName: "class_skill_levels_skill_level_id_fkey"
						columns: ["skill_level_id"]
						isOneToOne: false
						referencedRelation: "skill_levels"
						referencedColumns: ["id"]
					}
				]
			}
			classes: {
				Row: {
					id: string
					term_id: string
					name: string
					weekday: number
					start_time_local: string
					duration_minutes: number
					capacity: number
					default_court_id: string | null
					default_coach_id: string | null
					created_at: string
					updated_at: string
				}
				Insert: {
					id?: string
					term_id: string
					name: string
					weekday: number
					start_time_local: string
					duration_minutes: number
					capacity: number
					default_court_id?: string | null
					default_coach_id?: string | null
					created_at?: string
					updated_at?: string
				}
				Update: {
					id?: string
					term_id?: string
					name?: string
					weekday?: number
					start_time_local?: string
					duration_minutes?: number
					capacity?: number
					default_court_id?: string | null
					default_coach_id?: string | null
					created_at?: string
					updated_at?: string
				}
				Relationships: [
					{
						foreignKeyName: "classes_default_coach_id_fkey"
						columns: ["default_coach_id"]
						isOneToOne: false
						referencedRelation: "accounts"
						referencedColumns: ["id"]
					},
					{
						foreignKeyName: "classes_default_court_id_fkey"
						columns: ["default_court_id"]
						isOneToOne: false
						referencedRelation: "courts"
						referencedColumns: ["id"]
					},
					{
						foreignKeyName: "classes_term_id_fkey"
						columns: ["term_id"]
						isOneToOne: false
						referencedRelation: "terms"
						referencedColumns: ["id"]
					}
				]
			}
			court_availability: {
				Row: {
					id: string
					court_id: string
					weekday: number
					open_local: string
					close_local: string
					effective_from: string
					effective_to: string | null
					lesson_bookable: boolean
					slot_minutes: number
					reservation_ref: string | null
					created_by: string | null
					created_at: string
				}
				Insert: {
					id?: string
					court_id: string
					weekday: number
					open_local: string
					close_local: string
					effective_from: string
					effective_to?: string | null
					lesson_bookable?: boolean
					slot_minutes?: number
					reservation_ref?: string | null
					created_by?: string | null
					created_at?: string
				}
				Update: {
					id?: string
					court_id?: string
					weekday?: number
					open_local?: string
					close_local?: string
					effective_from?: string
					effective_to?: string | null
					lesson_bookable?: boolean
					slot_minutes?: number
					reservation_ref?: string | null
					created_by?: string | null
					created_at?: string
				}
				Relationships: [
					{
						foreignKeyName: "court_availability_court_id_fkey"
						columns: ["court_id"]
						isOneToOne: false
						referencedRelation: "courts"
						referencedColumns: ["id"]
					},
					{
						foreignKeyName: "court_availability_created_by_fkey"
						columns: ["created_by"]
						isOneToOne: false
						referencedRelation: "accounts"
						referencedColumns: ["id"]
					}
				]
			}
			court_availability_exceptions: {
				Row: {
					id: string
					court_id: string
					on_date: string
					kind: Database["public"]["Enums"]["availability_exception_kind"]
					open_local: string | null
					close_local: string | null
					reason: string | null
					created_by: string | null
					created_at: string
				}
				Insert: {
					id?: string
					court_id: string
					on_date: string
					kind: Database["public"]["Enums"]["availability_exception_kind"]
					open_local?: string | null
					close_local?: string | null
					reason?: string | null
					created_by?: string | null
					created_at?: string
				}
				Update: {
					id?: string
					court_id?: string
					on_date?: string
					kind?: Database["public"]["Enums"]["availability_exception_kind"]
					open_local?: string | null
					close_local?: string | null
					reason?: string | null
					created_by?: string | null
					created_at?: string
				}
				Relationships: [
					{
						foreignKeyName: "court_availability_exceptions_court_id_fkey"
						columns: ["court_id"]
						isOneToOne: false
						referencedRelation: "courts"
						referencedColumns: ["id"]
					},
					{
						foreignKeyName: "court_availability_exceptions_created_by_fkey"
						columns: ["created_by"]
						isOneToOne: false
						referencedRelation: "accounts"
						referencedColumns: ["id"]
					}
				]
			}
			courts: {
				Row: {
					id: string
					location_id: string
					name: string
					active: boolean
				}
				Insert: {
					id?: string
					location_id: string
					name: string
					active?: boolean
				}
				Update: {
					id?: string
					location_id?: string
					name?: string
					active?: boolean
				}
				Relationships: [
					{
						foreignKeyName: "courts_location_id_fkey"
						columns: ["location_id"]
						isOneToOne: false
						referencedRelation: "locations"
						referencedColumns: ["id"]
					}
				]
			}
			credit_ledger: {
				Row: {
					id: string
					player_id: string
					entry_type: Database["public"]["Enums"]["ledger_entry_type"]
					delta: number
					credit_kind: Database["public"]["Enums"]["credit_kind"]
					lot_id: string | null
					order_item_id: string | null
					stripe_payment_intent_id: string | null
					booking_session_id: string | null
					expires_at: string | null
					forgiven_skips: number | null
					idempotency_key: string
					reason: string | null
					created_by: string | null
					created_at: string
				}
				Insert: {
					id?: string
					player_id: string
					entry_type: Database["public"]["Enums"]["ledger_entry_type"]
					delta: number
					credit_kind: Database["public"]["Enums"]["credit_kind"]
					lot_id?: string | null
					order_item_id?: string | null
					stripe_payment_intent_id?: string | null
					booking_session_id?: string | null
					expires_at?: string | null
					forgiven_skips?: number | null
					idempotency_key: string
					reason?: string | null
					created_by?: string | null
					created_at?: string
				}
				Update: {
					id?: string
					player_id?: string
					entry_type?: Database["public"]["Enums"]["ledger_entry_type"]
					delta?: number
					credit_kind?: Database["public"]["Enums"]["credit_kind"]
					lot_id?: string | null
					order_item_id?: string | null
					stripe_payment_intent_id?: string | null
					booking_session_id?: string | null
					expires_at?: string | null
					forgiven_skips?: number | null
					idempotency_key?: string
					reason?: string | null
					created_by?: string | null
					created_at?: string
				}
				Relationships: [
					{
						foreignKeyName: "credit_ledger_booking_session_id_fkey"
						columns: ["booking_session_id"]
						isOneToOne: false
						referencedRelation: "sessions"
						referencedColumns: ["id"]
					},
					{
						foreignKeyName: "credit_ledger_created_by_fkey"
						columns: ["created_by"]
						isOneToOne: false
						referencedRelation: "accounts"
						referencedColumns: ["id"]
					},
					{
						foreignKeyName: "credit_ledger_lot_id_fkey"
						columns: ["lot_id"]
						isOneToOne: false
						referencedRelation: "credit_ledger"
						referencedColumns: ["id"]
					},
					{
						foreignKeyName: "credit_ledger_order_item_id_fkey"
						columns: ["order_item_id"]
						isOneToOne: false
						referencedRelation: "order_items"
						referencedColumns: ["id"]
					},
					{
						foreignKeyName: "credit_ledger_player_id_fkey"
						columns: ["player_id"]
						isOneToOne: false
						referencedRelation: "players"
						referencedColumns: ["id"]
					}
				]
			}
			guardianships: {
				Row: {
					id: string
					account_id: string
					player_id: string
					role: Database["public"]["Enums"]["guardianship_role"]
					started_at: string
					ended_at: string | null
				}
				Insert: {
					id?: string
					account_id: string
					player_id: string
					role: Database["public"]["Enums"]["guardianship_role"]
					started_at?: string
					ended_at?: string | null
				}
				Update: {
					id?: string
					account_id?: string
					player_id?: string
					role?: Database["public"]["Enums"]["guardianship_role"]
					started_at?: string
					ended_at?: string | null
				}
				Relationships: [
					{
						foreignKeyName: "guardianships_account_id_fkey"
						columns: ["account_id"]
						isOneToOne: false
						referencedRelation: "accounts"
						referencedColumns: ["id"]
					},
					{
						foreignKeyName: "guardianships_player_id_fkey"
						columns: ["player_id"]
						isOneToOne: false
						referencedRelation: "players"
						referencedColumns: ["id"]
					}
				]
			}
			lesson_bookings: {
				Row: {
					session_id: string
					session_type: Database["public"]["Enums"]["session_type"]
					player_id: string
					booked_by_account_id: string
					status: Database["public"]["Enums"]["booking_status"]
					credits_spent: number
					created_at: string
					updated_at: string
				}
				Insert: {
					session_id: string
					session_type?: Database["public"]["Enums"]["session_type"]
					player_id: string
					booked_by_account_id: string
					status?: Database["public"]["Enums"]["booking_status"]
					credits_spent?: number
					created_at?: string
					updated_at?: string
				}
				Update: {
					session_id?: string
					session_type?: Database["public"]["Enums"]["session_type"]
					player_id?: string
					booked_by_account_id?: string
					status?: Database["public"]["Enums"]["booking_status"]
					credits_spent?: number
					created_at?: string
					updated_at?: string
				}
				Relationships: [
					{
						foreignKeyName: "lesson_bookings_booked_by_account_id_fkey"
						columns: ["booked_by_account_id"]
						isOneToOne: false
						referencedRelation: "accounts"
						referencedColumns: ["id"]
					},
					{
						foreignKeyName: "lesson_bookings_player_id_fkey"
						columns: ["player_id"]
						isOneToOne: false
						referencedRelation: "players"
						referencedColumns: ["id"]
					},
					{
						foreignKeyName: "lesson_bookings_session_id_session_type_fkey"
						columns: ["session_id", "session_type"]
						isOneToOne: false
						referencedRelation: "sessions"
						referencedColumns: ["id", "session_type"]
					}
				]
			}
			locations: {
				Row: {
					id: string
					name: string
					address: string | null
					active: boolean
				}
				Insert: {
					id?: string
					name: string
					address?: string | null
					active?: boolean
				}
				Update: {
					id?: string
					name?: string
					address?: string | null
					active?: boolean
				}
				Relationships: []
			}
			marketing_consents: {
				Row: {
					account_id: string
					subscribed: boolean
					source: string | null
					updated_at: string
				}
				Insert: {
					account_id: string
					subscribed?: boolean
					source?: string | null
					updated_at?: string
				}
				Update: {
					account_id?: string
					subscribed?: boolean
					source?: string | null
					updated_at?: string
				}
				Relationships: [
					{
						foreignKeyName: "marketing_consents_account_id_fkey"
						columns: ["account_id"]
						isOneToOne: false
						referencedRelation: "accounts"
						referencedColumns: ["id"]
					}
				]
			}
			notification_sends: {
				Row: {
					id: string
					trigger_key: string
					category: Database["public"]["Enums"]["notify_category"]
					recipient_account_id: string
					player_id: string | null
					template: string
					status: Database["public"]["Enums"]["send_status"]
					provider_message_id: string | null
					created_at: string
					sent_at: string | null
				}
				Insert: {
					id?: string
					trigger_key: string
					category: Database["public"]["Enums"]["notify_category"]
					recipient_account_id: string
					player_id?: string | null
					template: string
					status?: Database["public"]["Enums"]["send_status"]
					provider_message_id?: string | null
					created_at?: string
					sent_at?: string | null
				}
				Update: {
					id?: string
					trigger_key?: string
					category?: Database["public"]["Enums"]["notify_category"]
					recipient_account_id?: string
					player_id?: string | null
					template?: string
					status?: Database["public"]["Enums"]["send_status"]
					provider_message_id?: string | null
					created_at?: string
					sent_at?: string | null
				}
				Relationships: [
					{
						foreignKeyName: "notification_sends_player_id_fkey"
						columns: ["player_id"]
						isOneToOne: false
						referencedRelation: "players"
						referencedColumns: ["id"]
					},
					{
						foreignKeyName: "notification_sends_recipient_account_id_fkey"
						columns: ["recipient_account_id"]
						isOneToOne: false
						referencedRelation: "accounts"
						referencedColumns: ["id"]
					}
				]
			}
			order_items: {
				Row: {
					id: string
					order_id: string
					product_id: string
					player_id: string
					quantity: number
					unit_amount_cents: number
				}
				Insert: {
					id?: string
					order_id: string
					product_id: string
					player_id: string
					quantity?: number
					unit_amount_cents: number
				}
				Update: {
					id?: string
					order_id?: string
					product_id?: string
					player_id?: string
					quantity?: number
					unit_amount_cents?: number
				}
				Relationships: [
					{
						foreignKeyName: "order_items_order_id_fkey"
						columns: ["order_id"]
						isOneToOne: false
						referencedRelation: "orders"
						referencedColumns: ["id"]
					},
					{
						foreignKeyName: "order_items_player_id_fkey"
						columns: ["player_id"]
						isOneToOne: false
						referencedRelation: "players"
						referencedColumns: ["id"]
					},
					{
						foreignKeyName: "order_items_product_id_fkey"
						columns: ["product_id"]
						isOneToOne: false
						referencedRelation: "products"
						referencedColumns: ["id"]
					}
				]
			}
			orders: {
				Row: {
					id: string
					account_id: string
					status: Database["public"]["Enums"]["order_status"]
					amount_total_cents: number
					currency: string
					stripe_checkout_session_id: string | null
					stripe_payment_intent_id: string | null
					created_at: string
					paid_at: string | null
					updated_at: string
				}
				Insert: {
					id?: string
					account_id: string
					status?: Database["public"]["Enums"]["order_status"]
					amount_total_cents?: number
					currency?: string
					stripe_checkout_session_id?: string | null
					stripe_payment_intent_id?: string | null
					created_at?: string
					paid_at?: string | null
					updated_at?: string
				}
				Update: {
					id?: string
					account_id?: string
					status?: Database["public"]["Enums"]["order_status"]
					amount_total_cents?: number
					currency?: string
					stripe_checkout_session_id?: string | null
					stripe_payment_intent_id?: string | null
					created_at?: string
					paid_at?: string | null
					updated_at?: string
				}
				Relationships: [
					{
						foreignKeyName: "orders_account_id_fkey"
						columns: ["account_id"]
						isOneToOne: false
						referencedRelation: "accounts"
						referencedColumns: ["id"]
					}
				]
			}
			players: {
				Row: {
					id: string
					full_name: string
					birthdate: string
					skill_level_id: string | null
					notes: string | null
					created_at: string
					updated_at: string
				}
				Insert: {
					id?: string
					full_name: string
					birthdate: string
					skill_level_id?: string | null
					notes?: string | null
					created_at?: string
					updated_at?: string
				}
				Update: {
					id?: string
					full_name?: string
					birthdate?: string
					skill_level_id?: string | null
					notes?: string | null
					created_at?: string
					updated_at?: string
				}
				Relationships: [
					{
						foreignKeyName: "players_skill_level_id_fkey"
						columns: ["skill_level_id"]
						isOneToOne: false
						referencedRelation: "skill_levels"
						referencedColumns: ["id"]
					}
				]
			}
			products: {
				Row: {
					id: string
					kind: Database["public"]["Enums"]["product_kind"]
					name: string
					description: string | null
					price_public_cents: number
					price_member_cents: number | null
					currency: string
					credit_kind: Database["public"]["Enums"]["credit_kind"] | null
					credit_quantity: number | null
					credit_validity_days: number | null
					forgiven_skips: number | null
					stripe_price_public: string | null
					stripe_price_member: string | null
					active: boolean
					created_at: string
					updated_at: string
				}
				Insert: {
					id?: string
					kind: Database["public"]["Enums"]["product_kind"]
					name: string
					description?: string | null
					price_public_cents: number
					price_member_cents?: number | null
					currency?: string
					credit_kind?: Database["public"]["Enums"]["credit_kind"] | null
					credit_quantity?: number | null
					credit_validity_days?: number | null
					forgiven_skips?: number | null
					stripe_price_public?: string | null
					stripe_price_member?: string | null
					active?: boolean
					created_at?: string
					updated_at?: string
				}
				Update: {
					id?: string
					kind?: Database["public"]["Enums"]["product_kind"]
					name?: string
					description?: string | null
					price_public_cents?: number
					price_member_cents?: number | null
					currency?: string
					credit_kind?: Database["public"]["Enums"]["credit_kind"] | null
					credit_quantity?: number | null
					credit_validity_days?: number | null
					forgiven_skips?: number | null
					stripe_price_public?: string | null
					stripe_price_member?: string | null
					active?: boolean
					created_at?: string
					updated_at?: string
				}
				Relationships: []
			}
			rating_dimensions: {
				Row: {
					id: string
					key: string
					label: string
					scale_max: number
					sort: number
					active: boolean
					updated_at: string
				}
				Insert: {
					id?: string
					key: string
					label: string
					scale_max?: number
					sort?: number
					active?: boolean
					updated_at?: string
				}
				Update: {
					id?: string
					key?: string
					label?: string
					scale_max?: number
					sort?: number
					active?: boolean
					updated_at?: string
				}
				Relationships: []
			}
			rating_events: {
				Row: {
					id: string
					player_id: string
					dimension_id: string
					value: number
					scale_max_snapshot: number
					coach_id: string
					visibility: Database["public"]["Enums"]["rating_visibility"]
					note: string | null
					rated_at: string
				}
				Insert: {
					id?: string
					player_id: string
					dimension_id: string
					value: number
					scale_max_snapshot: number
					coach_id: string
					visibility?: Database["public"]["Enums"]["rating_visibility"]
					note?: string | null
					rated_at?: string
				}
				Update: {
					id?: string
					player_id?: string
					dimension_id?: string
					value?: number
					scale_max_snapshot?: number
					coach_id?: string
					visibility?: Database["public"]["Enums"]["rating_visibility"]
					note?: string | null
					rated_at?: string
				}
				Relationships: [
					{
						foreignKeyName: "rating_events_coach_id_fkey"
						columns: ["coach_id"]
						isOneToOne: false
						referencedRelation: "accounts"
						referencedColumns: ["id"]
					},
					{
						foreignKeyName: "rating_events_dimension_id_fkey"
						columns: ["dimension_id"]
						isOneToOne: false
						referencedRelation: "rating_dimensions"
						referencedColumns: ["id"]
					},
					{
						foreignKeyName: "rating_events_player_id_fkey"
						columns: ["player_id"]
						isOneToOne: false
						referencedRelation: "players"
						referencedColumns: ["id"]
					}
				]
			}
			session_attendance: {
				Row: {
					session_id: string
					player_id: string
					present: boolean
					marked_by: string
					marked_at: string
					updated_at: string
				}
				Insert: {
					session_id: string
					player_id: string
					present: boolean
					marked_by: string
					marked_at?: string
					updated_at?: string
				}
				Update: {
					session_id?: string
					player_id?: string
					present?: boolean
					marked_by?: string
					marked_at?: string
					updated_at?: string
				}
				Relationships: [
					{
						foreignKeyName: "session_attendance_marked_by_fkey"
						columns: ["marked_by"]
						isOneToOne: false
						referencedRelation: "accounts"
						referencedColumns: ["id"]
					},
					{
						foreignKeyName: "session_attendance_player_id_fkey"
						columns: ["player_id"]
						isOneToOne: false
						referencedRelation: "players"
						referencedColumns: ["id"]
					},
					{
						foreignKeyName: "session_attendance_session_id_fkey"
						columns: ["session_id"]
						isOneToOne: false
						referencedRelation: "sessions"
						referencedColumns: ["id"]
					}
				]
			}
			session_skill_levels: {
				Row: {
					session_id: string
					skill_level_id: string
				}
				Insert: {
					session_id: string
					skill_level_id: string
				}
				Update: {
					session_id?: string
					skill_level_id?: string
				}
				Relationships: [
					{
						foreignKeyName: "session_skill_levels_session_id_fkey"
						columns: ["session_id"]
						isOneToOne: false
						referencedRelation: "sessions"
						referencedColumns: ["id"]
					},
					{
						foreignKeyName: "session_skill_levels_skill_level_id_fkey"
						columns: ["skill_level_id"]
						isOneToOne: false
						referencedRelation: "skill_levels"
						referencedColumns: ["id"]
					}
				]
			}
			sessions: {
				Row: {
					id: string
					session_type: Database["public"]["Enums"]["session_type"]
					starts_at: string
					ends_at: string
					court_id: string | null
					coach_id: string | null
					status: Database["public"]["Enums"]["session_status"]
					venue_note: string | null
					notes: string | null
					timespan: unknown | null
					created_at: string
					updated_at: string
				}
				Insert: {
					id?: string
					session_type: Database["public"]["Enums"]["session_type"]
					starts_at: string
					ends_at: string
					court_id?: string | null
					coach_id?: string | null
					status?: Database["public"]["Enums"]["session_status"]
					venue_note?: string | null
					notes?: string | null
					timespan?: never
					created_at?: string
					updated_at?: string
				}
				Update: {
					id?: string
					session_type?: Database["public"]["Enums"]["session_type"]
					starts_at?: string
					ends_at?: string
					court_id?: string | null
					coach_id?: string | null
					status?: Database["public"]["Enums"]["session_status"]
					venue_note?: string | null
					notes?: string | null
					timespan?: never
					created_at?: string
					updated_at?: string
				}
				Relationships: [
					{
						foreignKeyName: "sessions_coach_id_fkey"
						columns: ["coach_id"]
						isOneToOne: false
						referencedRelation: "accounts"
						referencedColumns: ["id"]
					},
					{
						foreignKeyName: "sessions_court_id_fkey"
						columns: ["court_id"]
						isOneToOne: false
						referencedRelation: "courts"
						referencedColumns: ["id"]
					}
				]
			}
			skill_levels: {
				Row: {
					id: string
					key: string
					label: string
					rank: number
					active: boolean
				}
				Insert: {
					id?: string
					key: string
					label: string
					rank: number
					active?: boolean
				}
				Update: {
					id?: string
					key?: string
					label?: string
					rank?: number
					active?: boolean
				}
				Relationships: []
			}
			staff_members: {
				Row: {
					account_id: string
					role: Database["public"]["Enums"]["staff_role"]
					created_at: string
				}
				Insert: {
					account_id: string
					role: Database["public"]["Enums"]["staff_role"]
					created_at?: string
				}
				Update: {
					account_id?: string
					role?: Database["public"]["Enums"]["staff_role"]
					created_at?: string
				}
				Relationships: [
					{
						foreignKeyName: "staff_members_account_id_fkey"
						columns: ["account_id"]
						isOneToOne: false
						referencedRelation: "accounts"
						referencedColumns: ["id"]
					}
				]
			}
			stripe_events: {
				Row: {
					id: string
					type: string
					payload: Json
					received_at: string
					processed_at: string | null
					status: string
					error: string | null
				}
				Insert: {
					id: string
					type: string
					payload: Json
					received_at?: string
					processed_at?: string | null
					status?: string
					error?: string | null
				}
				Update: {
					id?: string
					type?: string
					payload?: Json
					received_at?: string
					processed_at?: string | null
					status?: string
					error?: string | null
				}
				Relationships: []
			}
			team_members: {
				Row: {
					team_id: string
					player_id: string
					joined_at: string
					left_at: string | null
				}
				Insert: {
					team_id: string
					player_id: string
					joined_at?: string
					left_at?: string | null
				}
				Update: {
					team_id?: string
					player_id?: string
					joined_at?: string
					left_at?: string | null
				}
				Relationships: [
					{
						foreignKeyName: "team_members_player_id_fkey"
						columns: ["player_id"]
						isOneToOne: false
						referencedRelation: "players"
						referencedColumns: ["id"]
					},
					{
						foreignKeyName: "team_members_team_id_fkey"
						columns: ["team_id"]
						isOneToOne: false
						referencedRelation: "teams"
						referencedColumns: ["id"]
					}
				]
			}
			team_sessions: {
				Row: {
					session_id: string
					session_type: Database["public"]["Enums"]["session_type"]
					team_id: string
					kind: Database["public"]["Enums"]["team_session_kind"]
					opponent: string | null
					home_away: string | null
				}
				Insert: {
					session_id: string
					session_type?: Database["public"]["Enums"]["session_type"]
					team_id: string
					kind?: Database["public"]["Enums"]["team_session_kind"]
					opponent?: string | null
					home_away?: string | null
				}
				Update: {
					session_id?: string
					session_type?: Database["public"]["Enums"]["session_type"]
					team_id?: string
					kind?: Database["public"]["Enums"]["team_session_kind"]
					opponent?: string | null
					home_away?: string | null
				}
				Relationships: [
					{
						foreignKeyName: "team_sessions_session_id_session_type_fkey"
						columns: ["session_id", "session_type"]
						isOneToOne: false
						referencedRelation: "sessions"
						referencedColumns: ["id", "session_type"]
					},
					{
						foreignKeyName: "team_sessions_team_id_fkey"
						columns: ["team_id"]
						isOneToOne: false
						referencedRelation: "teams"
						referencedColumns: ["id"]
					}
				]
			}
			teams: {
				Row: {
					id: string
					name: string
					season: string
					description: string | null
					created_at: string
				}
				Insert: {
					id?: string
					name: string
					season: string
					description?: string | null
					created_at?: string
				}
				Update: {
					id?: string
					name?: string
					season?: string
					description?: string | null
					created_at?: string
				}
				Relationships: []
			}
			terms: {
				Row: {
					id: string
					name: string
					starts_on: string
					ends_on: string
				}
				Insert: {
					id?: string
					name: string
					starts_on: string
					ends_on: string
				}
				Update: {
					id?: string
					name?: string
					starts_on?: string
					ends_on?: string
				}
				Relationships: []
			}
			waiver_documents: {
				Row: {
					id: string
					slug: string
					title: string
					required_for_participation: boolean
					created_at: string
					updated_at: string
				}
				Insert: {
					id?: string
					slug: string
					title: string
					required_for_participation?: boolean
					created_at?: string
					updated_at?: string
				}
				Update: {
					id?: string
					slug?: string
					title?: string
					required_for_participation?: boolean
					created_at?: string
					updated_at?: string
				}
				Relationships: []
			}
			waiver_signatures: {
				Row: {
					id: string
					waiver_version_id: string
					player_id: string
					signer_account_id: string
					capacity: Database["public"]["Enums"]["signing_capacity"]
					signer_name_snapshot: string
					relationship_snapshot: Database["public"]["Enums"]["guardianship_role"]
					signed_at: string
					ip: string | null
					user_agent: string | null
				}
				Insert: {
					id?: string
					waiver_version_id: string
					player_id: string
					signer_account_id: string
					capacity: Database["public"]["Enums"]["signing_capacity"]
					signer_name_snapshot: string
					relationship_snapshot: Database["public"]["Enums"]["guardianship_role"]
					signed_at?: string
					ip?: string | null
					user_agent?: string | null
				}
				Update: {
					id?: string
					waiver_version_id?: string
					player_id?: string
					signer_account_id?: string
					capacity?: Database["public"]["Enums"]["signing_capacity"]
					signer_name_snapshot?: string
					relationship_snapshot?: Database["public"]["Enums"]["guardianship_role"]
					signed_at?: string
					ip?: string | null
					user_agent?: string | null
				}
				Relationships: [
					{
						foreignKeyName: "waiver_signatures_player_id_fkey"
						columns: ["player_id"]
						isOneToOne: false
						referencedRelation: "players"
						referencedColumns: ["id"]
					},
					{
						foreignKeyName: "waiver_signatures_signer_account_id_fkey"
						columns: ["signer_account_id"]
						isOneToOne: false
						referencedRelation: "accounts"
						referencedColumns: ["id"]
					},
					{
						foreignKeyName: "waiver_signatures_waiver_version_id_fkey"
						columns: ["waiver_version_id"]
						isOneToOne: false
						referencedRelation: "waiver_versions"
						referencedColumns: ["id"]
					}
				]
			}
			waiver_versions: {
				Row: {
					id: string
					document_id: string
					version: number
					content_md: string
					content_sha256: string
					published_at: string | null
					created_by: string | null
					created_at: string
				}
				Insert: {
					id?: string
					document_id: string
					version: number
					content_md: string
					content_sha256: string
					published_at?: string | null
					created_by?: string | null
					created_at?: string
				}
				Update: {
					id?: string
					document_id?: string
					version?: number
					content_md?: string
					content_sha256?: string
					published_at?: string | null
					created_by?: string | null
					created_at?: string
				}
				Relationships: [
					{
						foreignKeyName: "waiver_versions_created_by_fkey"
						columns: ["created_by"]
						isOneToOne: false
						referencedRelation: "accounts"
						referencedColumns: ["id"]
					},
					{
						foreignKeyName: "waiver_versions_document_id_fkey"
						columns: ["document_id"]
						isOneToOne: false
						referencedRelation: "waiver_documents"
						referencedColumns: ["id"]
					}
				]
			}
		}
		Views: {
			v_credit_balances: {
				Row: {
					player_id: string | null
					credit_kind: Database["public"]["Enums"]["credit_kind"] | null
					balance: number | null
					next_expiry: string | null
				}
				Relationships: []
			}
			v_current_ratings: {
				Row: {
					id: string | null
					player_id: string | null
					dimension_id: string | null
					value: number | null
					scale_max_snapshot: number | null
					coach_id: string | null
					visibility: Database["public"]["Enums"]["rating_visibility"] | null
					note: string | null
					rated_at: string | null
				}
				Relationships: []
			}
			v_current_waiver_versions: {
				Row: {
					waiver_version_id: string | null
					document_id: string | null
					version: number | null
				}
				Relationships: []
			}
			v_lot_remaining: {
				Row: {
					lot_id: string | null
					player_id: string | null
					credit_kind: Database["public"]["Enums"]["credit_kind"] | null
					expires_at: string | null
					issued_at: string | null
					issued: number | null
					remaining: number | null
				}
				Relationships: []
			}
			v_player_waiver_status: {
				Row: {
					player_id: string | null
					document_id: string | null
					slug: string | null
					waiver_version_id: string | null
					satisfied: boolean | null
				}
				Relationships: []
			}
		}
		Functions: {
			academy_local: {
				Args: {
					ts: string
				}
				Returns: string
			}
			academy_scope: {
				Args: {
					ts: string
				}
				Returns: Database["public"]["Enums"]["credit_scope"]
			}
			academy_tz: {
				Args: Record<PropertyKey, never>
				Returns: string
			}
			academy_week_start: {
				Args: {
					ts: string
				}
				Returns: string
			}
			apply_forgiveness: {
				Args: {
					p_booking: string
				}
				Returns: boolean
			}
			archive_player: {
				Args: {
					p_player: string
				}
				Returns: undefined
			}
			assert_waivers_signed: {
				Args: {
					p_player: string
				}
				Returns: undefined
			}
			book_class: {
				Args: {
					p_player: string
					p_session: string
				}
				Returns: string
			}
			book_private_lesson: {
				Args: {
					p_player: string
					p_coach: string
					p_court: string
					p_starts: string
					p_ends: string
					p_credits?: number
				}
				Returns: string
			}
			can_view_financials: {
				Args: {
					p_player: string
				}
				Returns: boolean
			}
			cancel_booking: {
				Args: {
					p_kind: string
					p_id: string
				}
				Returns: Json
			}
			cancel_session: {
				Args: {
					p_session: string
					p_reason?: string
				}
				Returns: number
			}
			court_available: {
				Args: {
					p_court: string
					p_start: string
					p_end: string
					p_for_lessons?: boolean
				}
				Returns: boolean
			}
			create_player: {
				Args: {
					p_full_name: string
					p_birthdate: string
					p_role: Database["public"]["Enums"]["guardianship_role"]
					p_skill_level_key?: string
				}
				Returns: string
			}
			expire_credits: {
				Args: Record<PropertyKey, never>
				Returns: number
			}
			finalize_bookings: {
				Args: {
					p_ended_before?: string
				}
				Returns: number
			}
			generate_class_sessions: {
				Args: {
					p_class: string
					p_from: string
					p_to: string
				}
				Returns: Json
			}
			guards: {
				Args: {
					p_player: string
				}
				Returns: boolean
			}
			is_admin: {
				Args: Record<PropertyKey, never>
				Returns: boolean
			}
			is_staff: {
				Args: Record<PropertyKey, never>
				Returns: boolean
			}
			issue_credits: {
				Args: {
					p_player: string
					p_kind: Database["public"]["Enums"]["credit_kind"]
					p_quantity: number
					p_idempotency_key: string
					p_product?: string
					p_order_item?: string
					p_stripe_pi?: string
					p_reason?: string
				}
				Returns: string
			}
			pick_lot: {
				Args: {
					p_player: string
					p_kind: Database["public"]["Enums"]["credit_kind"]
				}
				Returns: string
			}
			player_is_adult: {
				Args: {
					p_player: string
					p_at?: string
				}
				Returns: boolean
			}
			promote_waitlist: {
				Args: {
					p_session: string
				}
				Returns: number
			}
			set_player_level: {
				Args: {
					p_player: string
					p_skill_level_key: string
				}
				Returns: undefined
			}
			sign_waiver: {
				Args: {
					p_version: string
					p_player: string
					p_typed_name: string
					p_ip?: string
					p_user_agent?: string
				}
				Returns: string
			}
			update_player: {
				Args: {
					p_player: string
					p_full_name: string
					p_birthdate: string
				}
				Returns: undefined
			}
		}
		Enums: {
			availability_exception_kind: "closed" | "open"
			booking_status: "booked" | "waitlisted" | "completed" | "cancelled" | "cancelled_late" | "cancelled_by_academy" | "no_show"
			credit_kind: "class_weekday" | "class_weekend" | "private_lesson"
			credit_scope: "weekday" | "weekend"
			guardianship_role: "self" | "parent" | "legal_guardian" | "other"
			ledger_entry_type: "purchase" | "consume" | "consume_reversal" | "refund" | "expire" | "adjust" | "forgive"
			notify_category: "transactional" | "marketing"
			order_status: "pending" | "paid" | "partially_refunded" | "refunded" | "cancelled"
			product_kind: "class_pack" | "lesson_pack" | "camp" | "team_fee"
			rating_visibility: "internal" | "guardian"
			registration_status: "registered" | "waitlisted" | "cancelled"
			send_status: "pending" | "sent" | "failed"
			session_status: "scheduled" | "cancelled"
			session_type: "camp" | "class" | "team" | "private"
			signing_capacity: "self" | "guardian"
			staff_role: "coach" | "admin"
			team_session_kind: "practice" | "match"
		}
		CompositeTypes: Record<never, never>
	}
}

type DefaultSchema = Database['public']

export type Tables<T extends keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])> =
	(DefaultSchema['Tables'] & DefaultSchema['Views'])[T] extends { Row: infer R } ? R : never
export type TablesInsert<T extends keyof DefaultSchema['Tables']> =
	DefaultSchema['Tables'][T] extends { Insert: infer I } ? I : never
export type TablesUpdate<T extends keyof DefaultSchema['Tables']> =
	DefaultSchema['Tables'][T] extends { Update: infer U } ? U : never
export type Enums<T extends keyof DefaultSchema['Enums']> = DefaultSchema['Enums'][T]
export type Functions<T extends keyof DefaultSchema['Functions']> = DefaultSchema['Functions'][T]
